import { createRequire } from 'node:module'
const { chromium } = createRequire('D:/deepseek-harness-alpha5/node_modules/.pnpm/playwright@1.61.1/node_modules/playwright/package.json')('playwright')
const fs = await import('node:fs')
const DIST = 'D:/DSH_workspace/ef-tools/dist'
fs.mkdirSync('D:/DSH_workspace/.tmp-probe', { recursive: true })
const b = await chromium.launch({ channel: 'msedge', headless: true })
const pg = await b.newPage({ viewport: { width: 1560, height: 1000 } })
const errs = []
pg.on('pageerror', e => errs.push('ERR ' + e.message.slice(0, 150)))
await pg.route('**/*', async route => {
  const u = new URL(route.request().url())
  let p = u.pathname === '/' ? '/index.html' : u.pathname
  const fp = DIST + '/' + decodeURIComponent(p).replace(/^\//, '')
  if (!fs.existsSync(fp)) { await route.abort(); return }
  const ext = p.split('.').pop()
  const ct = ext === 'js' ? 'application/javascript' : ext === 'json' ? 'application/json' : ext === 'html' ? 'text/html; charset=utf-8' : ext === 'webp' ? 'image/webp' : ext === 'css' ? 'text/css' : 'application/octet-stream'
  await route.fulfill({ contentType: ct, body: fs.readFileSync(fp) })
})
const fails = []
const assert = (n, c, x) => { console.log((c ? 'PASS' : 'FAIL') + ' ' + n + (x ? ' | ' + x : '')); if (!c) fails.push(n) }
await pg.goto('https://ak.local/', { waitUntil: 'load', timeout: 60000 })
await pg.waitForTimeout(3000)
const txt0 = await pg.evaluate(() => document.body.innerText)
assert('图鉴网格渲染 32 卡', txt0.includes('干员图鉴') && txt0.includes('32'), '')
const cards = await pg.locator('.operator-card').count()
console.log('cards:', cards)
assert('档案卡存在', cards >= 32, String(cards))
const ivan = pg.locator('.operator-card', { hasText: '伊冯' }).first()
await ivan.click()
await pg.waitForTimeout(800)
const detail = await pg.evaluate(() => document.body.innerText)
assert('详情出现（伊冯身份区）', detail.includes('OPERATOR /') && detail.includes('伊冯'), '')
assert('详情区块齐全（等级/潜能5/装备/精英化/战斗+天赋+能力值）', detail.includes('当前等级') && detail.includes('上限 20') && detail.includes('潜能') && detail.includes('装备与基质') && detail.includes('精英化') && detail.includes('战斗技能') && detail.includes('天赋 · 基建 · 好感度') && detail.includes('力量') && detail.includes('好感度'), '')
assert('技能真名显示（伊冯-雀跃扳机）', detail.includes('雀跃扳机'), '')
const dossierW = await pg.evaluate(() => document.querySelector('main.dossier').getBoundingClientRect().width)
assert('详情面板占满右区（宽>900）', dossierW > 900, 'w=' + dossierW)
const seg5 = pg.locator('.rank-bar').first().locator('span').nth(4)
await seg5.click()
await pg.waitForTimeout(500)
const d1 = await pg.evaluate(() => JSON.parse(localStorage.getItem('ef-roster') || '{}')['伊冯'])
console.log('saved skills:', JSON.stringify(d1 && d1.skills))
assert('技能1 置 5 保存', d1 && d1.skills[0] === 5, JSON.stringify(d1 && d1.skills))
const elite = pg.locator('.elite-seg').nth(2)
await elite.click()
await pg.waitForTimeout(400)
const d2 = await pg.evaluate(() => JSON.parse(localStorage.getItem('ef-roster') || '{}')['伊冯'].promo)
assert('精英化 → 3', d2 === 3, String(d2))
const wpnSel = pg.locator('select').filter({ has: pg.locator('option:has-text("工业零点一")') }).first()
await wpnSel.selectOption('工业零点一')
await pg.waitForTimeout(400)
const d3 = await pg.evaluate(() => JSON.parse(localStorage.getItem('ef-roster') || '{}')['伊冯'].wpn.name)
const msSave = await pg.evaluate(() => JSON.parse(localStorage.getItem('ef-roster') || '{}')['伊冯'].mastery)
assert('专精数据存在', Array.isArray(msSave) && msSave.length === 4, JSON.stringify(msSave))
assert('武器下拉保存（官方武器名）', d3 === '工业零点一', d3)
await pg.screenshot({ path: 'D:/DSH_workspace/ak-tools/ocr-samples/ef-v2-demo.png' })
console.log('ERRS:', JSON.stringify(errs.slice(0, 3)))
await pg.evaluate(() => localStorage.removeItem('ef-roster'))
await b.close()
console.log(fails.length ? 'RESULT: FAIL ' + fails.length : 'RESULT: ALL PASS')
process.exit(fails.length ? 1 : 0)